name: 🐛 Bug Report
description: Report a bug or technical issue with the GCSim to GO-MultiOpt converter
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees:
    - TheBertDark

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and fix the issue.

    - type: dropdown
      id: bug-type
      attributes:
          label: Type of Bug
          description: What type of issue are you experiencing?
          options:
              - Conversion Error (incorrect output)
              - Character Not Supported
              - File Format Issue
              - UI/Interface Problem
              - Performance Issue
              - Other
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: A clear and concise description of what the bug is
          placeholder: Describe what happened and what you expected to happen
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to Reproduce
          description: Tell us how to reproduce this behavior
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Upload file '...'
              4. See error
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: What did you expect to happen?
          placeholder: A clear description of what you expected to happen
      validations:
          required: true

    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual Behavior
          description: What actually happened?
          placeholder: A clear description of what actually happened
      validations:
          required: true

    - type: textarea
      id: input-file
      attributes:
          label: Input File/Configuration
          description: If applicable, paste your GCSim configuration or describe the input
          placeholder: |
              Paste your GCSim config here or describe the input that caused the issue
              ```
              // Your GCSim config
              ```
          render: text

    - type: textarea
      id: output-received
      attributes:
          label: Output Received
          description: If applicable, paste the incorrect output you received
          placeholder: |
              Paste the output you received here
              ```
              // Output received
              ```
          render: text

    - type: textarea
      id: expected-output
      attributes:
          label: Expected Output
          description: If applicable, paste what the output should have been
          placeholder: |
              Paste what you expected the output to be
              ```
              // Expected output
              ```
          render: text

    - type: dropdown
      id: browser
      attributes:
          label: Browser
          description: Which browser are you using?
          options:
              - Chrome
              - Firefox
              - Safari
              - Edge
              - Other
      validations:
          required: true

    - type: input
      id: browser-version
      attributes:
          label: Browser Version
          description: What version of the browser are you using?
          placeholder: e.g., Chrome 120.0.6099.109

    - type: dropdown
      id: operating-system
      attributes:
          label: Operating System
          description: Which operating system are you using?
          options:
              - Windows
              - macOS
              - Linux
              - Other
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context about the problem here
          placeholder: Screenshots, error messages, console logs, etc.

    - type: checkboxes
      id: terms
      attributes:
          label: Checklist
          description: Please confirm the following
          options:
              - label: I have searched existing issues to make sure this is not a duplicate
                required: true
              - label: I have provided all the requested information above
                required: true
              - label: This issue is related to the GCSim to GO-MultiOpt converter functionality
                required: true
